### PR TITLE
Attempt to fix race and nullptr ctd in Hooks::UpdateCombatControllerSettings

### PR DESCRIPTION
**Pull request by AndbGame**
#2 

trying to test build with this changes

### CODE REVIEW

**Comment by KrisV-777** [comment]
The nullptr check in remove_these should be unnecessary, I have played extensively with the lock only implementation and didnt have any issues, in fact I dont even notice either of these pointers ever being null after adding the mutex
Are you certain this check is necessary?

**Comment by AndbGame** [comment]
I catch a CTD if use  lock, but without this checking for nullptr, but it is rarely, and not clear how reproduce (1 CTD after 1 week of playing). 
We can to not add this check, but then I advise adding logging for this case - to simplify the search for the reason if receive feedbacks with crashes.

**Comment by AndbGame** [comment]
```
Skyrim SSE v1.6.640
CrashLoggerSSE v1-12-1-0 Dec 22 2023 02:20:56

Unhandled exception "EXCEPTION_ACCESS_VIOLATION" at 0x7FF9C652E3E3 Acheron.dll+006E3E3	movups xmm0, [rbx+0x28] |  E:\andb_skyrim_3\projects\Acheron\src\Acheron\Hooks\Hooks.cpp:225 ?UpdateCombatControllerSettings@Hooks@Acheron@@CAXPEAVCharacter@RE@@@Z)

SYSTEM SPECS:
	OS: Майкрософт Windows 11 Pro v10.0.22631
	CPU: GenuineIntel 13th Gen Intel(R) Core(TM) i9-13900KF
	GPU #1: Nvidia AD103 [GeForce RTX 4080]
	GPU #2: Microsoft Basic Render Driver
	PHYSICAL MEMORY: 25.91 GB/63.78 GB
	GPU MEMORY: 12.40/14.66 GB

PROBABLE CALL STACK:
	[0] 0x7FF9C652E3E3  Acheron.dll+006E3E3	movups xmm0, [rbx+0x28] |  E:\andb_skyrim_3\projects\Acheron\src\Acheron\Hooks\Hooks.cpp:225 ?UpdateCombatControllerSettings@Hooks@Acheron@@CAXPEAVCharacter@RE@@@Z
	[1] 0x7FF7230DF32C SkyrimSE.exe+060F32C	mov eax, [rsi+0x204] |  sub_7FF6C5DFF2FF_60F32C -> 37350+0x10C	mov eax, [rsi+0x204]
	[2] 0x7FF72373C628 SkyrimSE.exe+0C6C628	mov ecx, [rbx+0x0C] |  sub_7FF6C645C575_C6C628 -> 69378+0xD8	mov ecx, [rbx+0x0C]
	[3] 0x7FF72373CBF1 SkyrimSE.exe+0C6CBF1	mov r15d, eax |  sub_7FF6C645C575_C6CBF1 -> 69380+0x361	mov r15d, eax
	[4] 0x7FF72373AF7A SkyrimSE.exe+0C6AF7A	movzx eax, byte ptr [rbx+0xA74] |  BSFile::seek_140C6ADB0_C6AF7A -> 69344+0x8A	movzx eax, byte ptr [rbx+0xA74]
	[5] 0x7FF723715E4D SkyrimSE.exe+0C45E4D	mov rcx, [0x00007FF725AD6898] |  StartAddress_0_140C45E10_C45E4D -> 68445+0x3D	mov rcx, [0x00007FF725AD6898]
	[6] 0x7FFAE8A2257D KERNEL32.DLL+001257D
	[7] 0x7FFAEA28AA58    ntdll.dll+005AA58
```

```
[13:27:39] [warning] Hooks::UpdateCombatControllerSettings attackedActor = nullptr
[13:27:39] [warning] Hooks::UpdateCombatControllerSettings targetActor = nullptr
```

related code:
https://github.com/AndbGame/Acheron/blob/d70963a1fcfb78c36e530b8d433198662e60d2d6/src/Acheron/Hooks/Hooks.cpp#L225

(and of course it seems to me that this problem should be solved in some other way, but I don't understand exactly how, i.e. in general, I think this is a workaround to avoid crashes)

**Comment by AndbGame** [comment]
By the way, I remembered. The above CTD occurred while saving and loading the game in the middle of the battle

**Pull request merged**
